/**
 * Ticker Constants
 * Known ticker symbols for autocomplete suggestions.
 * Separated from priceService to avoid server/client import conflicts.
 * Updated: 2025
 */

/** Known exchange mappings for common tickers */
const EXCHANGE_MAP: Record<string, string> = {
    // --- NASDAQ (Tech & Growth) ---
    AAPL: 'NASDAQ',
    MSFT: 'NASDAQ',
    GOOGL: 'NASDAQ',
    GOOG: 'NASDAQ',
    AMZN: 'NASDAQ',
    META: 'NASDAQ',
    TSLA: 'NASDAQ',
    NVDA: 'NASDAQ',
    NFLX: 'NASDAQ',
    AMD: 'NASDAQ',
    INTC: 'NASDAQ',
    PYPL: 'NASDAQ',
    ADBE: 'NASDAQ',
    CSCO: 'NASDAQ',
    CMCSA: 'NASDAQ',
    PEP: 'NASDAQ',
    COST: 'NASDAQ',
    AVGO: 'NASDAQ',
    QCOM: 'NASDAQ',
    TXN: 'NASDAQ',
    SBUX: 'NASDAQ',
    BND: 'NASDAQ',
    QQQ: 'NASDAQ',
    ISRG: 'NASDAQ',
    BKNG: 'NASDAQ',
    MDLZ: 'NASDAQ',
    AMGN: 'NASDAQ',
    GILD: 'NASDAQ',
    INTU: 'NASDAQ',
    MU: 'NASDAQ',
    ABNB: 'NASDAQ',
    ARM: 'NASDAQ',
    PANW: 'NASDAQ',
    LRCX: 'NASDAQ',
    KLAC: 'NASDAQ',
    SMH: 'NASDAQ',

    // --- NYSE (Blue Chips & Financials) ---
    JPM: 'NYSE',
    V: 'NYSE',
    JNJ: 'NYSE',
    WMT: 'NYSE',
    PG: 'NYSE',
    MA: 'NYSE',
    UNH: 'NYSE',
    HD: 'NYSE',
    DIS: 'NYSE',
    BAC: 'NYSE',
    XOM: 'NYSE',
    KO: 'NYSE',
    PFE: 'NYSE',
    VZ: 'NYSE',
    T: 'NYSE',
    MRK: 'NYSE',
    CVX: 'NYSE',
    WFC: 'NYSE',
    ABT: 'NYSE',
    TMO: 'NYSE',
    NKE: 'NYSE',
    MCD: 'NYSE',
    LLY: 'NYSE',
    DHR: 'NYSE',
    NEE: 'NYSE',
    PM: 'NYSE',
    UNP: 'NYSE',
    IBM: 'NYSE',
    RTX: 'NYSE',
    HON: 'NYSE',
    LOW: 'NYSE',
    CAT: 'NYSE',
    GE: 'NYSE',
    BA: 'NYSE',
    GS: 'NYSE',
    BLK: 'NYSE',
    MMM: 'NYSE',
    AXP: 'NYSE',
    SPGI: 'NYSE',
    ORCL: 'NYSE',
    CRM: 'NYSE',
    ABBV: 'NYSE',
    UBER: 'NYSE',
    PLTR: 'NYSE',
    C: 'NYSE',
    MS: 'NYSE',
    NOW: 'NYSE',
    WM: 'NYSE',
    SHOP: 'NYSE',
    SQ: 'NYSE',

    // --- ETFs (NYSEARCA - Most liquid US ETFs) ---
    SPY: 'NYSEARCA',
    VOO: 'NYSEARCA',
    VTI: 'NYSEARCA',
    IVV: 'NYSEARCA',
    VEA: 'NYSEARCA',
    VWO: 'NYSEARCA',
    VNQ: 'NYSEARCA',
    AGG: 'NYSEARCA',
    VIG: 'NYSEARCA',
    VYM: 'NYSEARCA',
    SCHD: 'NYSEARCA',
    VGT: 'NYSEARCA',
    XLK: 'NYSEARCA',
    XLF: 'NYSEARCA',
    XLE: 'NYSEARCA',
    XLV: 'NYSEARCA',
    XLI: 'NYSEARCA',
    XLY: 'NYSEARCA',
    XLP: 'NYSEARCA',
    ARKK: 'NYSEARCA',
    IWM: 'NYSEARCA',
    GLD: 'NYSEARCA',
    SLV: 'NYSEARCA',
    EEM: 'NYSEARCA',
    XLU: 'NYSEARCA',
    XLB: 'NYSEARCA',

    // --- BMV (Mexico - IPC & High Liquidity) ---
    WALMEX: 'BMV',
    AMX: 'BMV',
    FEMSA: 'BMV',
    CEMEX: 'BMV',
    BIMBO: 'BMV',
    GFNORTE: 'BMV',
    GMEXICO: 'BMV',
    GAP: 'BMV',
    ASUR: 'BMV',
    OMA: 'BMV',
    AC: 'BMV',
    KOF: 'BMV',
    ALSEA: 'BMV',
    'PE&OLES': 'BMV',
    LIVEPOL: 'BMV',
    GRUMA: 'BMV',
    LAB: 'BMV',
    VESTA: 'BMV',
    TLEVISA: 'BMV',
    BBAJIO: 'BMV',
    BOLSA: 'BMV',
    GCC: 'BMV',
    CUERVO: 'BMV',
    VOLAR: 'BMV',
    FIBRAPL: 'BMV',
    FIBRAMQ: 'BMV',
    FUNO: 'BMV',
    TERRA: 'BMV',
    DANHOS: 'BMV',
    KIMBER: 'BMV',
    ORGBIA: 'BMV',
    PINFRA: 'BMV',
    Q: 'BMV',
    R: 'BMV',
    CHDRAUI: 'BMV',
    GENTERA: 'BMV',
    SITES: 'BMV',
    ARA: 'BMV',
    AGUA: 'BMV',
};

/** List of known ticker symbols for autocomplete */
export const KNOWN_TICKERS = Object.keys(EXCHANGE_MAP).sort();
